---
- hosts: all
  sudo: true
  user: root
  tasks:
    - name: Install dependencies for rbenv
      yum: name={{ item }} state=latest
      with_items:
        - git
        - tar
        - gcc
        - make
        - libffi-devel
        - zlib-devel
        - openssl-devel
        - readline-devel
        - nginx

    - name: Rubyの存在確認
      shell: bash -lc 'which ruby'
      register: ruby_install
      failed_when: ruby_install.rc not in [0, 1]


    - name: Gitからrbenvをクローンする
      git: repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv
      when: ruby_install.rc == 1

    - name: rbenvビルドプラグインをクローンする
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build
      when: ruby_install.rc == 1

    #- shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
     # sudo: no

    #- shell: echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> ~/.bash_profile
     # sudo: no

    #- shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
     # sudo: no
    
    #- shell: source ~/.bash_profile
     # sudo: no

    - name: Set rbenv env file
      sudo: yes
      copy: src=rbenv.sh dest=/etc/profile.d mode=0775

    #- name: profile_init.sh内のREPLACE_EXECRBENVをrbenv initに置換する
    #  replace:  dest=/etc/profile.d/profile_init.sh regexp="^#REPLACE_EXECRBENV" replace='eval "$(rbenv init -)" >/dev/null 2>&1'

    - name: 2.2.5のインストール
      shell: /bin/bash -lc "rbenv install 2.2.5"
      sudo: yes
      when: ruby_install.rc == 1

    - name: rehashを行う
      shell: /bin/bash -lc "rbenv rehash"
      when: ruby_install.rc == 1

    - name: 2.2.5をデフォルトに設定
      command: /bin/bash -lc "rbenv global 2.2.5"
      when: ruby_install.rc == 1

    # おまけに開発に必要なパッケージをinstall
    - yum: name={{item}} state=latest
      with_items:
        - ruby-devel
        - rubygems 

    - name: Rails インストール -v '4.2.6'
      shell: /bin/bash -lc "gem install rails -v '4.2.6'"

    - name: unicorn インストール
      shell: /bin/bash -lc "gem install unicorn"

    - name: splite3 インストール
      shell: /bin/bash -lc "gem install sqlite3 -v '1.3.11'"

    - name: Railsアプリ ビルド
      shell: /bin/bash -lc "rails new app"
